### ISSUE TITLE
Add in-text citation capability for non-Grattan styles

### ISSUE THREAD

**Issue by wfmackey** [wfmackey/word2grattex#1]
Add in-text citation capability for non-Grattan (ie citation styles that aren't Style of Quiet Achievers). 

This is urgent for non-EndNote users, as there is no SOQA-equivalent citation style in Mendeley.

Will be implemented in `bib2grattex` by:  
1. Expanding `findCitation` options. For example, to include bracketed terms as found in the Harvard style: `(Norton & Cherastidtham 2018)`
1. increasing the options of authors in `findAuthor` to include three-or-more named authors.

**Comment by MattCowgill** [comment]
URGENT

**Comment by wfmackey** [comment]
@MattCowgill yes yes I'll add Harvard style today/tomorrow

**Comment by wfmackey** [comment]
Fixed in #12
