### ISSUE TITLE
Make build_tables better

### ISSUE THREAD

**Issue by wfmackey** [wfmackey/word2grattex#21]
* tbl labels
* Let pandoc have a go at creating the tables

**Comment by wfmackey** [comment]
Kinda fine as is tbh

**Comment by wfmackey** [comment]
Fix an error in it tho

**Comment by wfmackey** [comment]
THANK YOU @MattCowgill

**Comment by MattCowgill** [comment]
you're welcome @wfmackey, I'm here to help

**Comment by MattCowgill** [comment]
that was fast - I assigned you and then you closed the issue with a commit 1 minute later
