### ISSUE TITLE
Separate \footnote{...} lines

### ISSUE THREAD

**Issue by wfmackey** [wfmackey/word2grattex#3]
When a `\footnote{...}` is found, start a new line.

Requirement of `grattanReporter`, so needs to be done *either* manually or with `word2grattex`.

Hugh has done something like this.

**Comment by wfmackey** [comment]
@carmelachivers1 oh lol it was already on my to-do list.

**Comment by carmelachivers1** [comment]
Efficient!! Ticking things off without even knowing it

**Comment by MattCowgill** [comment]
g'day all

**Comment by wfmackey** [comment]
DONE CHECK IT OUT @MattCowgill @carmelachivers1 @jamesha95 @wfmackey 

``` r
word2grattex::add_footnote_newline("path/to/tex/file")
```

**Comment by carmelachivers1** [comment]
Sick one!!

**Comment by MattCowgill** [comment]
should the `texPath` argument include the filename (eg. 'dir/health.tex') or just the directory ('dir')

**Comment by MattCowgill** [comment]
just tried it out, it needs the filename. GOOD STUFF, WFM

**Comment by wfmackey** [comment]
Include the filename. I'll make that clearer in the doc.

**Comment by wfmackey** [comment]
Check if the `\footnote` (or a tab `\t` then `\footnote`) starts the line. If so, skip.
